name = "automated-dca-worker"
main = "src/index.ts"
compatibility_date = "2024-05-29"

# We run this once a week on Friday at 21:00 UTC (4:00 PM EST) to allow deposits to clear
# You can change this to suit your schedule
[triggers]
crons = ["0 21 * * 5"]

# We will inject the following securely via Cloudflare Secrets to keep them out of GitHub:
# EXCHANGE_API_KEY
# EXCHANGE_PRIVATE_KEY
# EXCHANGE_API_URL
# JWT_ISSUER
# RESEND_API_KEY
# NOTIFICATION_EMAIL
# BTC_DCA_AMOUNT
# ETH_DCA_AMOUNT
